# Generated by Django 5.1.7 on 2025-03-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generalsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralSubmission',
        ),
    ]
